# Generated by Django 3.2.8 on 2021-10-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='for_reh_001',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=194, unique=True, verbose_name='Função')),
                ('treinamento', models.CharField(blank=True, max_length=194, null=True, verbose_name='Treinamento requerido')),
                ('experiencia', models.CharField(blank=True, max_length=194, null=True, verbose_name='Experiência requerida')),
            ],
            options={
                'verbose_name': 'FOR-REH-001',
                'verbose_name_plural': 'FOR-REH-001',
                'db_table': 'for_reh_001',
            },
        ),
    ]
