# Generated by Django 3.2.8 on 2021-10-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaopessoas', '0002_for_reh_001_experienciaopc'),
    ]

    operations = [
        migrations.AddField(
            model_name='for_reh_001',
            name='escolaridade',
            field=models.CharField(choices=[('Alfabetizado', 'Alfabetizado'), ('Fundamental incompleto', 'Fundamental incompleto'), ('Fundamental completo', 'Fundamental completo'), ('Médio incompleto', 'Médio incompleto'), ('Médio completo', 'Médio completo'), ('Superior incompleto', 'Superior incompleto'), ('Superior completo', 'Superior completo')], default='', max_length=194, verbose_name='Escolaridade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='for_reh_001',
            name='treinamentoopc',
            field=models.CharField(choices=[('sim', 'sim'), ('não', 'não')], default='', max_length=5, verbose_name='Necessário treinamento'),
            preserve_default=False,
        ),
    ]
