# Generated by Django 3.2.8 on 2021-10-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tab_sgq_001',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisito_num_original', models.CharField(max_length=184, unique=True, verbose_name='N.Requisito(original)')),
                ('requisito_txt_original', models.TextField(verbose_name='Descrição do requisito (original)')),
                ('requirement_num_original', models.CharField(max_length=184, verbose_name='N.Requirement (original)')),
                ('requirement_txt_original', models.TextField(verbose_name='Requirement description (original)')),
            ],
            options={
                'verbose_name': 'TAB-SGQ-001',
                'verbose_name_plural': 'TAB-SGQ-001',
                'db_table': 'tab_sqg_001',
            },
        ),
    ]
